#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# cleaning solvers 

wclean libso libraries/porousBoundaryConditions
wclean libso libraries/porousModels
wclean all solvers
wclean all utilities
