#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# Parse arguments for library compilation
if [ -f $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments ]
then  . $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
fi

wmake all libraries
wmake all solvers
wmake all utilities
