#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# cleaning solvers 

wclean all solvers
wclean all libraries
wclean all utilities

# purge option to clean executables
if [ "$1" = "--purge" ]
then
    # clean solver executables
    rm -f $FOAM_USER_APPBIN/anisoImpesFoam
    rm -f $FOAM_USER_APPBIN/groundwater2DFoam
    rm -f $FOAM_USER_APPBIN/groundwaterFoam
    rm -f $FOAM_USER_APPBIN/groundwaterTransportFoam
    rm -f $FOAM_USER_APPBIN/impesFoam
    rm -f $FOAM_USER_APPBIN/porousScalarTransport2DFoam
    rm -f $FOAM_USER_APPBIN/porousScalarTransportFoam
    rm -f $FOAM_USER_APPBIN/stationaryGroundwater2DFoam
    rm -f $FOAM_USER_APPBIN/stationaryGroundwaterFoam
    # clean dynamic libraries
    rm -f $FOAM_USER_LIBBIN/libporousBoundaryConditions.so
    rm -f $FOAM_USER_LIBBIN/libporousModels.so
    rm -f $FOAM_USER_LIBBIN/libtoolsGIS.so
fi
