#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication groundwater2DFoam -steady
runApplication postProcess -func probes -latestTime
tail -1 postProcessing/probes/*/potential > potential_probes.dat
