#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

foamClearPolyMesh
rm -f log.*
rm -rf constant/g constant/transportProperties 1* 2* 3* 4* 5* 6* 7* 8* 9* 
rm -rf postProcessing
