/*---------------------------------------------------------------------------*\
  		  _______  ____    ____  ________  
 		 |_   __ \|_   \  /   _||_   __  | 
   		   | |__) | |   \/   |    | |_ \_| 
   		   |  ___/  | |\  /| |    |  _|    
    		  _| |_    _| |_\/_| |_  _| |_     
   		 |_____|  |_____||_____||_____|    
   	     Copyright (C) Toulouse INP, Pierre Horgue

License
    This file is part of porousMultiphaseFoam, an extension of OpenFOAM
    developed by Pierre Horgue (phorgue@imft.fr) and dedicated to multiphase 
    flows through porous media.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

 Class
    Foam::simpleMesh

Description
    A simple mesh class for solvers using multiMesh option.

SourceFiles
    simpleMesh.C

\*---------------------------------------------------------------------------*/

#ifndef simpleMesh_H
#define simpleMesh_H

#include "multiMesh.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
             Class porousMediumModel Declaration
\*---------------------------------------------------------------------------*/

class simpleMesh
:
    public multiMesh
{

    //- Disallow copy construct
    simpleMesh(const simpleMesh&) = delete;

    //- Disallow default bitwise assignment
    void operator=(const simpleMesh&) = delete;

public:

    //- Runtime type information
    TypeName("simpleMesh");

    //- Construct from components
    simpleMesh(dynamicFvMesh& mesh);

    //- Destructor
    virtual ~simpleMesh() {}

    //- Return the unique mesh (coarse one)s
    dynamicFvMesh& fineMesh() {return coarseMesh_;};
};

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
