#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# case 1 - no gravity

runApplication blockMesh
cp constant/g.case1 constant/g
runApplication impesFoam 
runApplication postProcess -func sampleDict
