#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -f log.* *.csv *.png debit.insat 0/phi 0/hwater 0/waterSourceTerm 0/seepageTerm 0/infiltration
rm -rf [1-9]* postProcessing
