#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
cp 0/Sb.org 0/Sb
cp constant/Winj.org constant/Winj
cp constant/Wext.org constant/Wext
cp 0/K.org 0/K
cp 0/eps.org 0/eps
runApplication setFields
runApplication anisoImpesFoam 
