#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# case 2 - with gravity

runApplication blockMesh
cp 0/Sw.org 0/Sw
cp 0/So.org 0/So
runApplication setFields
runApplication triImpesFoam
runApplication postProcess -func sampleDict
