#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
cp constant/z0.org constant/z0
cp 0/infiltration.org 0/infiltration
runApplication setFields
runApplication groundwater2DFoam
