#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
cp 0/Sb.org 0/Sb
cp constant/K.org constant/K
runApplication setFields
runApplication impesFoam 
