#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# case 2 - with gravity

runApplication blockMesh
cp 0/Sb.org 0/Sb
runApplication setFields
runApplication impesFoam
runApplication sample
