#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication groundwaterTransportFoam

./postProcess_dt.sh log.groundwaterTransportFoam

runApplication postProcess -func sampleDict
